trigger:
  branches:
    include:
      - main

variables:
  acrName: acrtaskappjunaid
  acrLoginServer: acrtaskappjunaid.azurecr.io
  backendImageName: taskapp-backend
  frontendImageName: taskapp-frontend
  backendAppName: app-taskapp-backend-junaid
  resourceGroup: rg-taskapp-student-junaid1
  tag: $(Build.BuildId)

stages:

# ─── Stage 1: Build & Push Backend ───────────────────────────────────────────
- stage: BuildBackend
  displayName: Build & Push Backend Image
  jobs:
  - job: BuildBackend
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Backend
      inputs:
        command: buildAndPush
        containerRegistry: acr-service-connection
        repository: $(backendImageName)
        dockerfile: backend/Dockerfile
        context: backend
        tags: |
          $(tag)
          latest

# ─── Stage 2: Build & Push Frontend ──────────────────────────────────────────
- stage: BuildFrontend
  displayName: Build & Push Frontend Image
  dependsOn: BuildBackend
  jobs:
  - job: BuildFrontend
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
        command: buildAndPush
        containerRegistry: acr-service-connection
        repository: $(frontendImageName)
        dockerfile: frontend/Dockerfile
        context: frontend
        tags: |
          $(tag)
          latest
        arguments: --build-arg VITE_API_URL=https://app-taskapp-backend-junaid-a8fjgwc6gmapfzfw.eastasia-01.azurewebsites.net

# ─── Stage 3: Deploy Backend to App Service ──────────────────────────────────
- stage: DeployBackend
  displayName: Deploy Backend to Azure App Service
  dependsOn: BuildFrontend
  jobs:
  - deployment: DeployBackend
    pool:
      vmImage: ubuntu-latest
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy Backend Container
            inputs:
              azureSubscription: azure-service-connection
              appName: $(backendAppName)
              resourceGroupName: $(resourceGroup)
              imageName: $(acrLoginServer)/$(backendImageName):$(tag)
